### ISSUE TITLE
delete all status project in one click

### ISSUE THREAD

**Issue by dhanyn10** [scout-app/scout-app#370] opened 2017-12-25 15:52 UTC
very helpful if there is a button to clear all notifications about the status of the project
![image](https://user-images.githubusercontent.com/11478316/34341254-2ab8e1b0-e9c6-11e7-938d-825af8679a52.png)

**Comment by TheJaredWilcurt** [comment] 2017-12-26 15:11
Closing as duplicate of #281

**Closed by TheJaredWilcurt** 2017-12-26 15:11 UTC
