### ISSUE TITLE
Sourcemaps not working in new version of Scout-app v2.18.16

### ISSUE THREAD

**Issue by smileyblonde1** [scout-app/scout-app#405] opened 2019-05-21 09:24 UTC
OS: 
Scout-App Version: 
Information from Dev Tools: 
Uninstalled v2.18.16 and installed v2.12.12 and everything working fine again. 

(Attach screenshot below)

**Comment by TheJaredWilcurt** [comment] 2019-05-23 21:53
Closing this as duplicate of #402

**Closed by TheJaredWilcurt** 2019-05-23 21:53 UTC
