### ISSUE TITLE
New Install - Error #3214

### ISSUE THREAD

**Issue by rrgrimm** [scout-app/scout-app#196] opened 2015-02-04 19:21 UTC
I am new to Scout. I install it, click + to create a new project and set up my input and output directories. When I click the button on the project to watch, I get this error in Adobe AIR Introspector:

[app:/views/production.html][11:09:57] ArgumentError: Error #3214
errorId   3214
getStackTrace   function Function() {}
   length    0
line    11
message    "Error #3214"
name    "ArgumentError"
sourceId    65238176
sourceURL    app:/javascripts/app/process_interaction.js

stackTrace    [Array 16]
0
functionName    startWatchingProject
line    11
sourceURL    app:/javascripts/app/process_interaction.js

**Comment by ArtbyArjan** [comment] 2015-02-05 12:24
This is caused by a different Java version.

Also see [#187](https://github.com/mhs/scout-app/issues/187)

**Comment by rrgrimm** [comment] 2015-02-05 15:32
Thank you, Arjan. I know what to do now!

Rick

**Comment by PetrusMGirnus** [comment] 2015-06-01 22:51
On Win  8:
Navigate to C:\Program Files (x86)\Scout\javascripts\app\process_interaction.js

make sure edit  security privilege so you can edit the code. On the very bottom is the function javaDir() 
go ahead make sure that the path matches the one in C:\Program Files (x86)\Java\jre1.8.0_45\bin.exe 

like so,

  if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe");

**Comment by DerekAllyson-LM** [comment] 2015-07-27 14:43
Thanks xPetrus, can't tell you how much time this saved me!

**Comment by xPetrus** [comment] 2015-07-27 15:06
No problem I'm glad I could help!

**Comment by pankaj20dec** [comment] 2015-11-10 01:20
Thanks It works for me.

**Comment by TheLaughingGod1986** [comment] 2016-02-05 02:40
I love this guy

**Comment by icaroguerreiro** [comment] 2016-02-25 18:30
thx Gothburz

**Comment by TheJaredWilcurt** [comment] 2016-08-28 23:43
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)

**Closed by TheJaredWilcurt** 2016-08-28 23:43 UTC
