### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by 12appletree** [scout-app/scout-app#395] opened 2018-10-18 09:49 UTC
Just installed Scout-app on Windows 7 (64 bit) - not so familiar with this kind of tools.
I try to compile my first project but get an error:
`Uncaught TypeError: undefined is not a function`
see screenshot
![error1](https://user-images.githubusercontent.com/11877504/47146130-b4e68380-d2cb-11e8-9dcf-c8a17ed2c1ed.jpg)

**Comment by TheJaredWilcurt** [comment] 2018-10-19 19:00
@12appletree 

Have you been able to get it to work yet? I am unable to reproduce this. The specific error is saying that when you click the play icon in the sidebar to run a project, it tries to run the code `scout.helpers.startWatching(id);`, but it can't find `scout.helpers`. Which is defined before the sidebar code is ever loaded, so it should have no problem finding this.

The specific line ([`sidebar.js:68`](https://github.com/scout-app/scout-app/blob/v2.12.12/scout-files/_scripts/sidebar.js#L68)) has not changed since the first release of Scout-App 2. You are the first person to report this bug, so I assume it's something specific to your machine/OS/environment.

**Comment by TheJaredWilcurt** [comment] 2019-03-17 16:13
@12appletree 

Closing issue. There has been a new release of **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**. If issue still exists, create a new issue with steps to reproduce.

**Closed by TheJaredWilcurt** 2019-03-17 16:13 UTC
Labels: possible-bug

**Comment by TheJaredWilcurt** [comment] 2019-10-23 19:21
Issue was reported on Oct. 11, 2019 in Gitter chat. User was in Window 10 when it happened, but could not give additional details to reproduce.
