### ISSUE TITLE
Hot-reloading

### ISSUE THREAD

**Issue by lordcatalien** [scout-app/scout-app#334] opened 2017-05-11 22:11 UTC
I'm curious if there's a plan (or way) to hot-reload the site after compiling the SASS like node can.

**Comment by TheJaredWilcurt** [comment] 2017-05-12 01:44
I think you are confused on what Node.js is. Node is just JavaScript that can be ran outside of a browser and has some extra features (I/O, hardware, OS, networking access).

There are modules (libraries) written with Node that allow for live reloading or hot reloading (not the same thing).

There is a plan to offer live reloading in a future version of Scout-App.

Closing this issue as a duplicate of #39.

**Closed by TheJaredWilcurt** 2017-05-12 01:44 UTC
Labels: feature-request
