### ISSUE TITLE
Source Map path wrong

### ISSUE THREAD

**Issue by briancbiggs** [scout-app/scout-app#359] opened 2017-11-08 18:06 UTC
OS: Windows 10
Scout-App Version: 2.12.12

I have a scss input folder that is: /the-liberator/scss, with the output path being the folder above it: /the-liberator. So, my file /the-liberator/scss/style.scss becomes /the-liberator/style.css. But, at the end of the output css (style.css) is: /*# sourceMappingURL=../style.map */. BUT, it should be this: /*# sourceMappingURL=style.map */. 

style.css and style.map are in the same directory.
But the path being produced to style.map is relative to style.scss, and not the outputted style.css. If you change the output directory, the source map url should change to reflect that.

Thanks.

**Comment by vishalp36** [comment] 2017-12-14 10:47
Can anyone fix this bug ASAP?

**Comment by TheJaredWilcurt** [comment] 2017-12-15 14:28
Confirmed this occurs. Have not found root cause yet and if it is happening due to Scout-App code or Node-Sass code.

Current work around is to create a sass and css folder next to each other and set the output to the css folder. (naming of folders is completely arbitrary, as long as they are siblings at the same level of hierarchy).

**Comment by freedompower** [comment] 2018-01-10 14:12
I can confirm I have the same bug.

**Comment by reknoZ** [comment] 2018-02-15 23:45
I confirm I have the same bug. Work-around also confirmed. But, I'd like to restore my folder structure:

/css/scss with the style.css and style.map ending up in /css/.

**Comment by TheJaredWilcurt** [comment] 2018-03-17 12:49
This bug has been fixed. it turns out we were using `outfile` instead of `outFile`. Fix is in the latest master branch code and will be included in the next release of Scout-App.

If you want to use the latest version, prior to the release:

1. Download and install [Node.js](http://nodejs.org)
2. Download the latest Scout-App [source code zip](https://github.com/scout-app/scout-app/archive/master.zip)
3. Extract the `scout-app-master` folder from the zipped source code
4. Navigate to the `scout-app-master` folder in your command line/terminal
5. Run `npm install` (will take a few minutes)
6. Run `npm start`

**Comment by TheJaredWilcurt** [comment] 2019-03-17 15:21
@briancbiggs @vishalp36 @freedompower @reknoZ 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.

**Closed by TheJaredWilcurt** 2019-03-17 15:21 UTC
Labels: confirmed-bug
