### ISSUE TITLE
Error (0x01) - Line: xx Col xx - File to import not found or unreadable

### ISSUE THREAD

**Issue by lad33** [scout-app/scout-app#274] opened 2016-10-19 10:32 UTC
Hi,

I've installed the latest Scout app (WIN_Scout-App_2.6.8) and am having problems getting it to work.  I never had a problem with the old Scout app (0.7.1) that used Adobe Air and Java, but as I'm starting out on a new computer build I don't want to install Java this time around bearing in mind all the security concerns it causes.

So I've added my current project that I'd backed up before rebuilding my computer.

Within my project I've the sub-folders:-

/library/scss

and 

/library/css 

within scss I have, as example, two scss files:-

style.scss

and 

_base.scss

When I try to amend content in _base.scss I get an error in Scout:-

Error (0x01) - Line:32 Col: 1
File to import not found or unreadable: base
Parent style sheet:
## style.scss

31: // styles in base.scss
32: @import "base";

---

I've searched for similar errors, tried (for the sake of argument) changing line 32 to @import "_base" or "_base.scss", and then tried deleting the .sass-cache folder hoping that it might have been causing the problem due to it caching (possibly) the old folder structure to which this project was within before I had to wipe my computer.

I cannot seem to figure this out, am I missing something obvious please?

**Comment by TheJaredWilcurt** [comment] 2016-10-19 18:46
I am unable to reproduce this issue. I assume that you have a syntax error in your code somewhere and that the error it's giving is unrelated. This error is generated by `Node-Sass`, Scout-App just surfaces it and makes it easier to parse.

![274](https://cloud.githubusercontent.com/assets/4629794/19532635/957b0aac-960a-11e6-924c-5a299ddbb3ad.png)

If this isn't an accurate reproduction of your issue, please upload a version that allows me to reproduce your bug..

**Comment by leewaring** [comment] 2016-10-26 15:37
I have this error. I found that I had to use the full path starting from C:/ ... / ... / all the way to the file.

Is this an issue or does the scout app support relative paths?

The old scout app accepted paths starting from the Input folder but this ones doesn't seem too.
Also on windows installation. Downloaded it today.

**Comment by TheJaredWilcurt** [comment] 2016-10-26 17:36
@lad33 @leewaring 

![relative](https://cloud.githubusercontent.com/assets/4629794/19737298/e1271b96-9b80-11e6-9e1b-ed16dfd869fc.png)

Scout-App 2 fully supports relative and direct links.

We have some [Testing](https://github.com/scout-app/scout-app/tree/master/Testing) folders in the repo that we use to make sure it works correctly before doing a release.

Again, this is likely a syntax error in your code that is causing this. If you can give me a project that causes this issue so I can reproduce it locally, I can verify if this is an error in your code, or if there is a legitimate bug in Scout-App that needs fixed for the next release.

**Comment by leewaring** [comment] 2016-10-27 07:54
My project is set up like this:

Website (output folder)
- _SCSS (Input folder)
-- Global
--- base.scss
-- css
--- _functions
---- colours.scss
---- fonts.scss
---- mixins.scss
---- functions-all.scss
--- _modules
--- etc...
- css (outputted CSS files)
- Global (outputted CSS files)

My base.scss file looks like this
/* ==== Import all functions */
@import 'css/_functions/functions-all';

/* ==== Import code modules */
@import 'css/_modules/core/normalise';
@import 'css/_modules/core/fonts';
@import 'css/_modules/core/core-element-styles';
@import 'css/_modules/core/helper-classes';
@import 'css/_modules/core/typesetting';
@import 'css/_modules/core/links';
@import 'css/_modules/core/layout';
@import 'css/_modules/core/sitefinity-layout-overwrites';
@import 'css/_modules/core/mobile-menu-button';
@import 'css/_modules/core/common-element-styles';
@import 'css/_modules/core/cookie-bar';
@import 'css/_modules/core/header-footer';
@import 'css/_modules/core/buttons';
@import 'css/_modules/core/print';

Does this help?

**Comment by TheJaredWilcurt** [comment] 2016-10-27 12:41
@leewaring 

I made a video to help explain what's going on:

* https://youtu.be/FD6G2Yveigs

**Comment by leewaring** [comment] 2016-10-27 13:13
Thanks for the video! Cleared up a few things which have been bugging me.

So it seems on the version of Scout that I was running the path to imported files could be either relative, direct or relative to the input folder (kind of like setting a HTML base tag as a reference point).
In all of my scss files I could use `@import 'css/_functions/functions-all';` and it would import the functions-all scss file no matter how far down the document tree the file was saved as it would start at the Input folder and work from there.
I liked this feature as I didn't have to worry about changing the path or if I moved the scss file to another folder up or down the document tree I wouldn't have to change the import path to the functions file.

I agree my project is set up rather strange however in the CMS I am using (Sitefinity) the _SCSS folder is located in the root of the template folder. The template folder requires a Global folder (with capital G) of which any css files placed within will be loaded onto all pages. I then created a css folder in the root to house the page specific css files. It's rather a large site with over 100 style sheets so far so I'm keen on keeping order and making files easy to find. That said I have only been using scss for 6-8 months so still lots to learn!

**Comment by TheJaredWilcurt** [comment] 2016-10-27 14:18
@leewaring 

Cool, glad that cleared things up. I won't be changing the way Scout-App 2 looks for files. The current process is handled completely by Node-Sass. It would take a lot of extra work to circumvent their built in system which would lead to a much buggier app.

Scout-App does a lot to make things easier for people, but changing this would just encourage bad habits and make it harder to transition a Sass code base from Scout-App to a different system like Webpack/Grunt/Gulp. Your Sass files and structure should follow the Sass standards and be agnostic towards what system you are using to process them.

**Comment by TheJaredWilcurt** [comment] 2016-10-27 14:34
@lad33

Let me know if that video helps you too. If so I can close this issue.

**Comment by leewaring** [comment] 2016-10-27 15:01
@TheJaredWilcurt 

I may have stumbled upon a solution to this problem. It looks as though using // at the start of the path will make it look for the file from the input folder path. So I would need to update my import paths to `//css/_functions/functions-all`

I would wonder if this would also work on Webpack/Grunt/Gulp too?

**Comment by leewaring** [comment] 2016-10-28 08:13
That's a shame. I can't change to Scout app 2 if it doesn't offer the same functionality of its predecessor. Does Scout work because it creates a cache file just below the input folder?

I'll keep an eye on this project though and try it out for my other sites.

Thanks for all your help and advice. Really appreciate it.

**Comment by TheJaredWilcurt** [comment] 2016-10-28 13:14
* **Scout-App Classic** was built on Java, Adobe Air, and Ruby (Ruby Sass).
* **Scout-App 2** is built on [NW.js](http://nwjs.io), Node, and Node-Sass (SassC).

The two share no code in common. Scout-App 2 was a complete rewrite to allow us to take advantage of modern (2016) Sass, since Scout-App Classic was stuck on a 2012 version of Sass that could not be updated. It also allowed us many other advantages, like better cross-platform support and easier developing. Though we've kept the design very similar, and have the same beliefs that drove Scout-App Classic, it simply cannot function identically due to the drastically different underlying technologies.

There is a basic comparison chart on [Scout-App.io](http://scout-app.io/#whatsnew) between the two.

It should be noted that Compass is Ruby only, so many projects that relied on it, also would need to be modified to use Scout-App 2. Fortunately (for Scout-App 2), the industry as a whole has been moving away from Compass over the last few years, so complaints about this have been very few.

I hope Scout-App 2 can accommodate your future workflows.

**Comment by TheJaredWilcurt** [comment] 2016-10-31 17:54
@leewaring 

This isn't exactly what you were describing, but is related, so I thought I would let you know about it, since this feature isn't documented anywhere and may be of use to you:

* https://github.com/scout-app/scout-app/issues/275#issuecomment-257368181

**Comment by lad33** [comment] 2016-11-01 09:14
Hi, apologies for the delay in getting back in touch on this one...

I've had a read through of thread and watched the first half of the video however leewaring's setup looks a little more complex than mine so I'm thinking the cause for him may be different, or at least, my root problem is a variation on the theme.

Anyway...

Looking at my structure again, maybe I'm missing the obvious.

I have a project folder, within it the subfolder "library" as follows:-

project
= library
== css (Output folder)
== scss (Input folder)

Within the "scss" folder I have several files as example:-

scss
= _base.scss
= _grid.scss
= _mixins.scss
= style.scss

Incidentally, this structure is from a Wordpress theme called bones, I've been using as a project base.

Within style.scss, the following code snippet:-

// styles in base.scss
@import "base";

Hopefully, I've attached the style.scss file for easier reference:-
[style.scss.txt](https://github.com/scout-app/scout-app/files/563655/style.scss.txt)

So, reading through the thread, and looking at the video I'm not sure my issue is the same as discussed, with both the _base.scss file and the style.scss file both sitting in the Input folder (scss) I'm thinking the absolute/relative path clarification isn't the issue?

From my limited understanding but what I've managed to pick up so far with Sass and using Scout previously, I'm thinking the idea of the structure and code is that all the _xxxx.scss have been set up as separation of concerns to keep code segmented and easier to maintain within the theme. The style.scss is the file that then collates these files and in turn Scout then "translates" that file into the equivalent (and compressed in my instance) style.css which is then created/updated into the output folder (css) from which Wordpress can apply the styling etc.  The underscore tells Scout to ignore the other files because I don't want them in the output folder, only the "compiled" css stytesheet from style.scss.

I think that's about right?

So, I'm stuck trying to understand the error when the style.scss is trying to import a file within the same folder as itself.

Does that help any further at all?

Thanks for taking the time to assist us with this.

**Comment by TheJaredWilcurt** [comment] 2016-11-01 13:30
@lad33 

https://youtu.be/HF7-ryb9HPw

**Comment by lad33** [comment] 2016-11-01 14:29
Hi,

Thanks again for picking this up and for taking the time to put the video together too. Much appreciated.

Sounds good advice so I'll schedule some time to do exactly that and hopefully it won't take me long before I track down the culprit.

I'll comment back when I've done so for feedback.

Cheers.

**Comment by VladG0r** [comment] 2016-12-04 23:44
Windows8.1(64), (WIN_Scout-App_2.6.8)
--------------------------------------------
I have similar problem.
When i add a new project and run it first time - i hear success sound and i see my code in generated styles.css [my first screenshot].
But then, when i make any changes and click ctrl+S in my text-editor - i head error sound and see an error(in dev tools) [my first screenshot].
--------------------------------------------
I think the problem is - window-style path to my folder. 
Scout-App opened it as: F:/Projects/test/
Win explorer gives me: F:\Projects\test\
![first-pass](https://cloud.githubusercontent.com/assets/24376817/20870155/8d453ff4-bace-11e6-9147-43318d1420aa.png)
![second-pass](https://cloud.githubusercontent.com/assets/24376817/20870154/8d44f6ac-bace-11e6-9cd2-3cd1c901a45f.png)

**Comment by VladG0r** [comment] 2016-12-05 01:21
I just found: if i write my code using any other text editor (Notepad++, Brackets) - everything works perfect, i can save and see generated code in styles.css.
Sublime Text - still locking my styles.scss file for Scout-app.

**Comment by TheJaredWilcurt** [comment] 2016-12-05 01:41
@VladG0r

Though I'm still trying more thorough tests to attempt to reproduce this, my assumption is that it is related to `atomic saves`. This is enabled by default in Sublime in older versions, as of 3072 though it is disabled by default.

Scout-App uses `chokidar` to monitor changes on the file system (so when you save, it triggers the input to be processed again.)

* https://www.npmjs.com/package/chokidar#errors

According to their documentation, you could  add `atomic: true,` to line [180 of Scout-App/scout-files/_scripts/app.js](https://github.com/scout-app/scout-app/blob/v2.6.8/scout-files/_scripts/app.js#L180) in your copy of the application. (Either above or after the `ignored` line).

You could try that and see if Sublime works with that setting enabled. If so, I can look into maybe adding a setting for it in the Scout-App preferences. Or you can try disabling the setting in Sublime Text, as detailed here:

* http://stackoverflow.com/questions/20634684/what-is-sublime-text-doing-when-i-save-a-file

Or you could try updating to a never version of Scout-App that has it disabled by default.

**Comment by VladG0r** [comment] 2016-12-05 01:59
You were right.
Sublime Text 3 (beta build 3126) has "atomic_save": false, by default.
Changed it to :true and magic happend. You saved my day, Thanks!
![settings](https://cloud.githubusercontent.com/assets/24376817/20871491/2b21b6fe-bae2-11e6-9f8f-39c78fa23004.png)

**Comment by TheJaredWilcurt** [comment] 2016-12-05 23:52
@lad33 

Is the issue resolved for you?

**Comment by lad33** [comment] 2017-01-18 10:27
@TheJaredWilcurt 

Hi, I've done the same as VladG0r and changed the automic_save setting in Sublime Text 3 (beta build 3126) and I'm now not receiving the error.

Instead I'm receiving another error "Undefined variable: "{insert_variable_name}" in _base.scss for a variable declared in a separate mixin file _mixins.scss.

So I'm thinking the solution above has likely solved the problem stated therefore in this post but will need to test fully once I've resolved this new issue.

Thanks.

**Comment by TheJaredWilcurt** [comment] 2017-01-18 14:45
@lad33 if you have difficulty resolving the issue, link to a repo with the code in it, or zip and upload it and I'll take a look.

**Comment by lad33** [comment] 2017-01-20 09:51
@TheJaredWilcurt Thanks.  I figured it out, just needed to set aside some time properly and catch my brain up as it'd been a while since I last had chance to look at the problem.

I'd simply forgotten that all my other partials were commented out in my style.scss file including the _mixins.scss where the variables are defined! Doh!

Once I'd uncommented the file everything worked as it should.

**Comment by TheJaredWilcurt** [comment] 2017-01-20 20:05
Awesome. Closing this issue.

**Closed by TheJaredWilcurt** 2017-01-20 20:05 UTC
Labels: possible-bug, waiting-for-response

**Comment by smuuf** [comment] 2017-07-16 20:47
Having this issue when using vscode. 🤕

**Comment by andreasjhagen** [comment] 2017-07-21 15:58
Yep, same here. Im an error from time to time, telling me scout cant find the file. Stopping and restarting Scout usually solves the problem then but its getting pretty annoying after a while

**Comment by datacubed** [comment] 2021-04-11 13:57
I still get this issue with vscode.
It's not all the files - which is odd. But it happens in my main .scss where I import others. What is weird though is when I delete everything in the file, it still errors.

Even stranger (maybe?) I edit this file, ctrl+s - error sound + error message, then click a different scss file, ctrl+s, successful sound, and the css has been built.

**Comment by adrianovarlotta** [comment] 2022-04-11 19:01
> I still get this issue with vscode. It's not all the files - which is odd. But it happens in my main .scss where I import others. What is weird though is when I delete everything in the file, it still errors.
> 
> Even stranger (maybe?) I edit this file, ctrl+s - error sound + error message, then click a different scss file, ctrl+s, successful sound, and the css has been built.

Me too, i still get this issue with vscode.
