### ISSUE TITLE
Scout stops compiling scss file to css

### ISSUE THREAD

**Issue by tmddev** [scout-app/scout-app#434] opened 2021-02-25 07:54 UTC
Hi - just in case anyone else finds this issue on a search for Atom and/or saving and compiling scss to css with Scout.

I had a working scss file that was repeatedly saving and compiling to css without issue - all worked well. This suddenly stopped and Scout would seemingly not compile the same scss file, even after saves with a different text editor, restarts, recreations; even installation of a different compiler...

I later discovered a line of whitespace characters in the scss file that were stopping the compiling - ie compiling was reaching that point and stopping. Changes above that point were reflected but not below.

No errors were thrown (by either compiler - Scout or Koala).

I discovered this by accident using Firefox inspector which showed non alphanumeric characters in the css and red dots in the scss source. 

Deleting this whitespace from the scss file returned normal operations.

How they got there? - I suspect either a copy/paste from inspector or something during an Atom save (using Ftp-Remote-edit plugin).

Hope this saves someone else some head-scratching.

**Comment by TheJaredWilcurt** [comment] 2021-02-25 18:31
Closing as duplicate of #380

**Closed by TheJaredWilcurt** 2021-02-25 18:31 UTC
