### ISSUE TITLE
Scout watch and rewrite error

### ISSUE THREAD

**Issue by Shwetha9** [scout-app/scout-app#392] opened 2018-07-10 04:01 UTC
Doesn't rewrite CSS until I stop and play again ... please help. Looks like a bug? I'm using Scout for OSX.

**Comment by TheJaredWilcurt** [comment] 2018-07-12 12:31
Closing as duplicate of https://github.com/scout-app/scout-app/issues/333

**Closed by TheJaredWilcurt** 2018-07-12 12:31 UTC
Labels: confirmed-bug
