### ISSUE TITLE
File to read not found

### ISSUE THREAD

**Issue by septillion-git** [scout-app/scout-app#323] opened 2017-02-23 20:46 UTC
Hi,

I realy like Scout! But I have a little problem. I have a intermediate error. I use Notepad++ to edit the .cscc and when I save a lot of times the .css is generated just fine.

But sometimes it fails without an error in log of the project. If I then go to Scout and stop and start again it generates the .css including a success message. Or, I could make same fake edits (aka, with the same end result as what I started with) and resave the file. Something it then generates the file, sometimes it fails again.

If I open the dev tools I have the following in the console:
```
Error {status: 4, message: "File to read not found or unreadable: D:/DOCUMENTE…Webs/Beneluxspoor remake/site/scss/index-new.scss", formatted: "Internal Error: File to read not found or unreadab…ebs/Beneluxspoor remake/site/scss/index-new.scss↵", stack: (...)}
```

I can expand it but I have no idea how to copy the whole log 👼 

Do you have any idea what the problem is? The need to restart Scout manually all the time is a bit annoying 😞

**Comment by TheJaredWilcurt** [comment] 2017-02-28 22:17
The error you are getting in the console is coming from `Node-Sass`. Scout-App is built on top of it, so we take the project settings you've set in the UI (the input/output folders, dev/prod, and output style), and pass that information along to Node-Sass.

For some reason, it looks like Node-Sass cannot see your file.

This may be related to "atomic saves" which some editors use. I'm not sure if Notepad++ does or not, but I was able to reproduce the scenario you are referring to, however I could not get any error messages to occur in the console. I was able to start up a project, it would run, then make changes to a file and save, but nothing would happen in Scout-App.

Scout-App uses `chokidar` to monitor for file changes in the input folder. It has some settings for atomic saves. I'll need to play around with this to see if there are any changes. If that's where the problem lies, then I can work that setting into Scout-App's UI.

**Comment by septillion-git** [comment] 2017-03-03 08:39
Hi,

Thanks for looking into this! Really like the simplicity of Scout 😄 

What you say sounds plausible indeed . If you need any more info from me or my console, just let me know!

**Comment by TheJaredWilcurt** [comment] 2018-02-26 13:48
Linkng to #333.

@septillion-git 

If you are still having this issue, I have added a setting for atomic save delays to the UI. Try this and let me know if it works:

1. Install [Node](https://nodejs.org/en/download) if you don't have it.
1. [Download the latest dev version of Scout-App](https://github.com/scout-app/scout-app/archive/master.zip).
1. Unzip, open cmd/terminal, navigate to the folder.
1. Then run `npm install`. (will take several minutes to complete)
1. Run `npm start` and test it.
1. Report back if it worked.

**Comment by TheJaredWilcurt** [comment] 2019-03-17 16:44
@septillion-git 

Closing this issue. There is a new release of [Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16). It contains a setting to control Atomic Save delays. You can try that out. If the issue persists in the latest version of Scout-App, you can create a new issue or reopen this one.

**Closed by TheJaredWilcurt** 2019-03-17 16:44 UTC
Labels: confirmed-bug, waiting-for-response

**Comment by septillion-git** [comment] 2019-03-23 17:07
Hi, thanks for letting me know! And sorry for my late reply 😳 

At the moment I'm not really doing any web related stuff and thus don't use Scout. But I will keep it in mind! Thanks!
