### ISSUE TITLE
Internal Error: File to read not found or unreadable

### ISSUE THREAD

**Issue by huydtq1996** [scout-app/scout-app#390] opened 2018-06-15 13:36 UTC
I created a simple website for my exercise yesterday. But there was an error when saving the scss file. Please check the description for more information, thank you.
[Description Video](https://www.youtube.com/watch?v=sMY43vv2FsY)

**Comment by TheJaredWilcurt** [comment] 2018-06-16 14:19
I recreated your set up on Windows 10 64-Bit and tested it in v2.12.12 and with the latest code from the `master` branch:

* [390.zip](https://github.com/scout-app/scout-app/files/2108189/390.zip)

I could not reproduce the issue. What seems to be happening is that everything is being processed twice. You can see this when you first start running the project it processes the `style.scss` file twice. Later when you make a change in a file, Chokidar picks up the change and cues Scout-App to run Node-Sass again. It looks like it's trying to run it twice at the same time, so one of them finishes first and the other gets confused and logs an error.

I'm not sure what is causing this for you. Possibly having two instances of Scout-App running at once. You could close/exit Scout-App and then check the Task Manager to see if it is still running. It could be something caused by your text editor making multiple writes to disk, or something based around atomic saves.

**Comment by huydtq1996** [comment] 2018-06-17 14:59
I just checked your files and it has the same errors with my original files.
I keep Scout-App running and the error occurred. I don't know why?
[Test Result](https://www.youtube.com/watch?v=dWo8PBEqKig)

**Comment by huydtq1996** [comment] 2018-06-17 15:07
The error occurred after I changed the scss file, and the compilation was only successful when I first ran it

**Comment by TheJaredWilcurt** [comment] 2018-06-17 18:54
@huydtq1996 

In the Task Manager, you would need to check the "Details" tab to see if there are multiple instances running. You should see 3 or 4 `Scout-App.exe`'s runnning when you open it. If you see 5 or more, then that means you have multiple instances running and will need to close them (right-click > end process tree). You could just need to right-click on Scout-App and "Run As Administrator".

I think more likely though, this is an issue with how your text editor is writing to the file. The first time you click the Run button for a project is just processes all the files on it's own, after that it listens for changes in files in the input directory. It is seeing multiple changes at once. This could be related to "atomic saves" or "atomic writes". You could try changing settings in your text editor to enablde or disable atomic saves. and see if that effects the issue.

There is an option in the upcoming version of Scout-App that you can adjust for this too. To try out the latest code for Scout-App:

1. Download the latest code from master:
   * https://github.com/scout-app/scout-app/archive/master.zip
2. Unzip that to it's own folder.
3. Install Node.js
   * https://nodejs.org
4. In command prompt (`cmd`) navigate to the folder and run the command `npm install`
5. From this point on to start the app you would run `npm start`

In the settings, there will be a slider for atomic saves, try adjusting it to different levels and see if it has any effect.

**Comment by TheJaredWilcurt** [comment] 2019-03-17 16:20
@huydtq1996 

Closing issue. There has been a new release of **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**. If the issue is related to atomic saves that setting is now available. If issue still exists in the latest version, we can reopen this issue or create a new one.

**Closed by TheJaredWilcurt** 2019-03-17 16:20 UTC
