### ISSUE TITLE
Scout Stops Work

### ISSUE THREAD

**Issue by Scoutankixsofia** [scout-app/scout-app#373] opened 2018-01-19 14:42 UTC
OS: 
Scout-App Version: WIN_Scout-App_2.12.12

When we do "Start" the application going down

Thanks

**Comment by TheJaredWilcurt** [comment] 2018-01-25 14:10
@Scoutankixsofia 

1. What operating system are you on (XP, 7, 8, 8.1, 10).
1. Is it 32 or 64 bit.
1. If you create a simplified project structure, does it still crash or is it unique to your project.
1. If it only happens on your project, can you narrow down the cause by removing files/lines of code that are unrelated.
1. Does it crash in older versions of Scout-App

**Comment by syb-lex** [comment] 2018-12-12 09:09
Hello!
Similar problem.
If my scss file has the string "content: "«";"
when we do "Start" the program disappears.
If I remove the symbol, change the line to "content:"";", then everything works well.
Win 7 64, Scout-App V2.12.12

**Comment by TheJaredWilcurt** [comment] 2018-12-12 15:42
Unable to reproduce. I created the following 4 files:

* `a.sass`
    ```sass
    .example
        content: "«"
    ```
* `b.sass`
    ```sass
    .example
        content: '«'
    ```
* `c.scss`
    ```scss
    .example {
        content: "«";
    }
    ```
* `d.scss`
    ```scss
    .example {
        content: '«';
    }
    ```

All four processed correctly in both Scout-App 2.12.12 and latest code from master branch.

**Comment by TheJaredWilcurt** [comment] 2019-03-17 16:28
Closing issue. New release of Scout-App is available. **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.

**Closed by TheJaredWilcurt** 2019-03-17 16:28 UTC
Labels: possible-bug, waiting-for-response
