### ISSUE TITLE
Getting "ArgumentError: Error #3214"

### ISSUE THREAD

**Issue by Made-of-Clay** [scout-app/scout-app#187] opened 2014-10-28 17:57 UTC
Whenever I try to start watching files for updates (i.e.g pressing the "play" button), I get this error from Adobe Air. I tried updating Air to see if that would fix the problem, but it did not. Also of note, when clicking the play button, it disappears after the error message pops up.

I'm running on Windows 7. I've included a screenshot of the error.

Thanks in advance for any help/advise.

![scoutissue_](https://cloud.githubusercontent.com/assets/8458698/4813787/9d650880-5ecb-11e4-8258-424e547c0405.JPG)

**Comment by getnathans** [comment] 2015-01-07 22:52
I know this is a late reply. i think the issue is SCOUT has a file called "process_interaction.js" and it uses set of hard corded paths to get java in users machine. So you will have to change that to point your java in that file.

**Comment by sg1010** [comment] 2015-01-17 20:30
This is what worked for me in Win8.1
from getnathans above:  SCOUT has a file called "process_interaction.js" ....

  function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
		path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_25\\bin\\java.exe");
      if(!path.exists){

**Comment by EraYaN** [comment] 2015-01-20 16:31
Please sir developer, add this to the settings or use the JAVA_HOME environment variable.

**Comment by Made-of-Clay** [comment] 2015-01-20 16:42
This doesn't really solve the issue, but I figured I would share. I just ended up learning the command line. It isn't terribly difficult, though the Scout tool was quite handy. Hope the bug gets fixed regardless.

**Comment by rtro92** [comment] 2015-02-11 01:35
I'm trying to edit the Javascript as mentioned above, but I when I save an error pops up saying 'Cannot save, Permission is denied'. Has anyone found a work around to this? Or a solution?

**Comment by xlsmile** [comment] 2015-02-16 23:33
Thanks everyone for contribution. The sg100's solution (providing the right path to newly updated Java in "C:\Program Files (x86)\Java\...") definitely helped in my case.

Cheers!

**Comment by beliya** [comment] 2015-02-24 09:43
Yes Yes thank you  getnathans 

 C:\Program Files (x86)\Scout\javascripts\app   has  "process_interaction.js" file and search this function 

function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre1.8.0_31\\bin\\java.exe");
      if(!path.exists)

and find your java folder in C:\Program Files\Java\jre1.8.0_31\bin\java.exe

make shoure jre folder \bin 
copy file path and past it in to js file, after add extra "\" to like under file path 
C:\\Program Files\\Java\\jre1.8.0_31\\bin\\java.exe

cheer

**Comment by Nordicdesign** [comment] 2015-04-21 15:01
Found the same issue on Win8.1 as I updated Adobe Air (Scout was running perfectly until then).
Tried updating Java but that didn't help. 

The solution suggested by sg1010 helped, but in my case I had to change the URL to
C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe

So check your Java path and update it accordingly.

**Comment by digiTeam** [comment] 2015-04-22 10:14
Thanks beliya that has fixed the issue for me

**Comment by PetrusMGirnus** [comment] 2015-06-01 22:35
Can confirm that Nordicdesigns works with Win 8:

function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre7\\bin\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre6\\bin\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

**Comment by nashCode** [comment] 2015-06-03 15:41
Thanks, works for me win 7:

function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre1.8.0_31\\bin\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_31\\bin\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre6\\bin\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

**Comment by WayneMcKenzie** [comment] 2015-06-06 15:18
Is anyone having problems with the stop button not showing up?

**Comment by andrewbiddinger** [comment] 2015-06-15 14:10
Yes, WayneMcKenzie. I am having problems with the stop button not showing up too. (As well as the "Error #3214")

**Comment by WayneMcKenzie** [comment] 2015-06-15 14:20
I've resorted to using mixture. Works just as well if not better.

http://mixture.io/

**Comment by andrewbiddinger** [comment] 2015-06-15 14:21
Ok, I'll check it out! Thanks, Wayne! My problems were fixed in Windows by updating my Java to v7.

**Comment by vipergirl77** [comment] 2015-07-15 00:22
I opened "processing_interaction.js" in my text editor, and changed the path, but when I try to save the changes it doesn't work. It seems like I need administrator permission. Help!

**Comment by xlsmile** [comment] 2015-07-15 00:38
@vipergirl77  Yes, you need to run your editor as an Admin. If you are on Windows right click your app, and choose "Run as administrator". On Widows 8 you can also press Windows Key, start typing your app name (eg Notepad++, Notepad etc), and when the app appears in search results, right click the app and then "run as administrator". Hope, that helps.

**Comment by vipergirl77** [comment] 2015-07-15 01:25
@xlsmile Ah okay, it works now. Thank you!

**Comment by gildniy** [comment] 2015-08-06 18:21
This really helped me a lot!
Thanks to you all!

**Comment by mayan62** [comment] 2015-08-16 00:07
Thank you soooo much  solved it finally! I had to change the path for the Java in the scoutj avafile

**Comment by DigiMouse** [comment] 2015-08-20 12:46
Hi, I have managed to update the path to below:

```javascript

function javaDir() {
  if(air.Capabilities.os.match(/Windows/)) {
    path = air.File.applicationDirectory.resolvePath("C:\Program Files\Java\jre7\bin\java.exe");
  if(!path.exists){
    path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_60\bin\java.exe");
  if(!path.exists){
    path = air.File.applicationDirectory.resolvePath("C:\Program Files\Java\jre6\bin\java.exe");
  }
}
  return path;
    } else {
  return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
}

```

Still with no luck, does anyone have any ideas? 

Im on windows 10 with Version 8 Update 60.

Thanks
Craig

**Comment by beliya** [comment] 2015-08-21 03:17
Pls check your java path

**Comment by gmt-it** [comment] 2015-08-21 04:35
You should use slash ( / ) instead of backslash. Works without Problems on WIN 10.

<pre>
function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre7/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre7/bin/java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre1.8.0_60/bin/java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }
</pre>

**Comment by Grahamhoare** [comment] 2015-09-09 14:08
Yes, Get nathans and beliya, this worked for me too! Dont forget its a double  \  for each folder in the path! You should just replicate the exisitng path structure you see but change the folder names as required, phew!

**Comment by spa** [comment] 2015-10-17 17:09
Had to edit the third path to the proper java version folder, otherwise @gmt-it 's solution was the only one that worked for me in Win10. Thanks!

**Comment by sarbjit399** [comment] 2015-11-21 17:54
Thanks... worked for me :)
- I just changed the paths from
<pre>function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre7\\bin\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_66\bin\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre6\\bin\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }</pre> 

to 
<pre>function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre1.8.0_66/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre1.8.0_66/bin/java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre1.8.0_66/bin/java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }</pre>

**Comment by Liriant** [comment] 2015-11-24 02:33
Running it as administrator and changing the variables fixed this issue for me.

**Comment by dim00** [comment] 2015-12-18 01:20
Windows 10 + Java 8

SOLUTION:
Open:  'C:\Program Files (x86)\Scout\javascripts\app\process_interaction.js' 

Change the line below according your version of Java AND you need to use DOUBLE-SLASHES - '\\':
if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_66\\bin\\java.exe");

Don't try to re-write the existing file, as you will get an error.
Just use 'Save As' for that. Then simply replace the files.

All the best!

**Comment by KennethHooper** [comment] 2016-01-05 13:56
Is there a permanent fix for this? Every time there is a Java update, the file needs to be modified.

Is there a way to change "path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_66\bin\java.exe");" to have some sort of wildcard or regex for \jre1.8.0_66\?

Any help would be appreciated.

Thanks!

**Comment by arctwelve** [comment] 2016-01-15 15:38
For future updates to Scout, suggest that Scout checks if Java is found when Scout loads. 

If not, allow the user to navigate to the java.exe within the configure screen.

**Comment by dongorous** [comment] 2016-01-22 06:54
For window 8, all you need to is change the path
    "C:\\Program Files\\Java\\jre7\\bin\\java.exe"

to 
    C:\Program Files\Java\jre1.8.0_60\bin\java.exe,

then instead of back slash "\" change it to forward slash "/" just like this
   C:/Program Files/Java/jre1.8.0_60/bin/java.exe

----------------------------------------------------------

function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre1.8.0_60/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre7\\bin\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre6\\bin\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

**Comment by larr** [comment] 2016-01-25 16:28
Great article fixes my problem on windows 10

**Comment by kziper1414** [comment] 2016-01-28 10:59
THIS WORKS ON ME windows 10, use double '/' 
change only on this :::> path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_66\bin\java.exe");  <:: dont change if(air.Capabilities.os.match(/Windows/)) { the double slash here.

thankx 
dim00 commented on Dec 17, 2015 
Windows 10 + Java 8

SOLUTION:
Open: 'C:\Program Files (x86)\Scout\javascripts\app\process_interaction.js'

Change the line below according your version of Java AND you need to use DOUBLE-SLASHES - '\':
if(air.Capabilities.os.match(/Windows/)) {
path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_66\bin\java.exe");

Don't try to re-write the existing file, as you will get an error.
Just use 'Save As' for that. Then simply replace the files.

P.S. I don't know why but github shows only one slash here instead of double.

All the best!

**Comment by KennethHooper** [comment] 2016-01-28 14:26
I think everyone is still missing the original question I posted. 

I know you can put in the current Java version and move on. I am looking for a solution that does NOT require me to change the version every time I update Java in Windows.

Thanks!

**Comment by arctwelve** [comment] 2016-02-02 00:23
@KennethHooper It's clear the solution hasn't been yet been implemented in this _free_, _opensource _software.

**Comment by hardstonepaul** [comment] 2016-02-03 20:07
Thanks for  me work!. With double **\\\**
Win 8.1 Java 8 Update 71

`function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\\Program Files\\\Java\\\jre7\\\bin\\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\\Program Files (x86)\\\Java\\\jre1.8.0_71\\\bin\\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\\Program Files\\\Java\\\jre1.8.0_71\\\bin\\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  } 
Take care with the Double '\\\' because GitHub change '\\\' for '\\'

**Comment by TheJaredWilcurt** [comment] 2016-08-29 00:04
@andrewbiddinger @arctwelve @beliya @digiTeam @dim00 @dongorous @EraYaN @getnathans @ghost @gildniy @gmt-it @Gothburz @Grahamhoare @hardstonepaul @iamabeagle @KennethHooper @kziper1414 @larr @Liriant @mayan62 @Made-of-Clay @nashCode @nfonte @Nordicdesign @rokkitpress @sarbjit399 @sg1010 @spa @WayneMcKenzie @xlsmile 

Wow, that's a lot of people. And I've got good news for all of you! :smile: 

Scout-App is no longer reliant on Adobe Air or Java! Try out the latest version and let us know what you think.

* [Scout-App.io](http://Scout-App.io)

If you have any feedback, create a new issue. Closing this one.

**Closed by TheJaredWilcurt** 2016-08-29 00:04 UTC

**Comment by e11world** [comment] 2018-05-11 21:11
@kziper1414 Thanks for your solution. It worked for me but even without the double slashes.
